name: Tests

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        timeout-minutes: 3
        run: npm run test
